from __future__ import annotations

# AUTOLEDGER R9 COMPLETE HELP
# Every user-facing feature should have a plain-language help topic.
# The tutorial deliberately walks every topic; searchable help uses the same source.

COMPLETE_HELP_TOPICS = (
    {'id':'welcome','title':'What AUTOLEDGER does','page':'dashboard','keywords':'start beginner purpose autoledger bank statement csv pastel','body':'AUTOLEDGER helps you turn bank statement transactions into accounting-ready Pastel cash-book import files. You load a supported bank CSV, review each payment and receipt, allocate the correct GL account and VAT treatment, validate the selected rows, and export. Nothing is posted to Pastel automatically: you still review the exported batch before processing it.'},
    {'id':'workflow','title':'The complete workflow','page':'dashboard','keywords':'workflow steps load review allocate select validate export','body':'Use this order every time: 1) choose the correct company profile, 2) check Settings, 3) load the bank CSV, 4) review Payments and Receipts, 5) fix unassigned or wrong allocations, 6) tick the rows you want to export, 7) Validate, 8) Export to Pastel, 9) import the Payment CSV on Pastel\'s Payments side and the Receipt CSV on the Receipts side, and 10) review the Pastel batch before processing it.'},
    {'id':'company_profiles','title':'What a company profile is','page':'dashboard','keywords':'company profile workspace separate company database','body':'A company profile is a separate accounting workspace. Use one profile for each company whose bank transactions you process. Each profile keeps its own rules, settings, history and saved session so transactions from different companies do not mix.'},
    {'id':'profile_buttons','title':'New, Rename and Delete company','page':'dashboard','keywords':'new rename delete profile default company','body':'New creates another company profile. Rename changes the name of the current profile. Delete removes a profile after confirmation; the original Default profile cannot be deleted, so rename Default to the company name instead. Switching profiles saves the current session but clears the statement from the screen while the other profile opens.'},
    {'id':'dashboard','title':'Accounting workspace and dashboard','page':'dashboard','keywords':'accounting workspace dashboard what should i do next current statement recommended workflow','body':'The Accounting workspace is the home page. It shows the current statement, a recommended workflow and a What should I do next? area. Use it when you are unsure what step comes next; the buttons take you to Load, Payments, Receipts, Validation, Export and Help.'},
    {'id':'ui_modes','title':'Modern UI and Classic UI','page':'dashboard','keywords':'modern classic interface view sidebar workspace','body':'Modern UI and Classic UI are two layouts for the same data. Changing the view does not move, copy or change your company information. Use whichever layout you find easier.'},
    {'id':'load_csv','title':'Load bank CSV / Load statement','page':'dashboard','keywords':'load bank csv statement supported file import','body':'Load bank CSV or Load statement opens a file picker so you can choose a supported bank CSV. AUTOLEDGER reads the transactions, separates money out into Payments and money in into Receipts, then applies saved rules for the current company profile. If the file contains no recognised bank transactions, AUTOLEDGER warns you rather than pretending the load succeeded.'},
    {'id':'payments_receipts','title':'Payments and Receipts / Money In','page':'payments','keywords':'payment receipt money out money in debit credit','body':'Payments are money leaving the bank account. Receipts / Money In are money entering the bank account. Always check you are working on the correct side because the two exported Pastel files are imported into different sides of the cash book.'},
    {'id':'transaction_table','title':'How to read a transaction row','page':'payments','keywords':'table date details amount gl vat rule status transaction columns','body':'Each row represents one bank transaction. Read the date, bank details, amount, GL account, VAT, rule and status columns before export. A row can be automatically allocated, manually allocated, corrected, ambiguous or still unassigned.'},
    {'id':'export_tick','title':'The export checkbox','page':'payments','keywords':'checkbox tick selected export include untick','body':'The empty/ticked box controls whether that transaction will be included in the next export. Ticked means selected for export; empty means not selected. Allocating a GL account does not automatically mean you have approved the row for export, so check the tick as well.'},
    {'id':'status_colors','title':'Colours and transaction status','page':'payments','keywords':'orange green unassigned assigned ambiguous corrected auto status','body':'Orange means the row still needs a usable GL allocation. Green/assigned means an allocation exists, but you must still review it. Ambiguous means saved rules disagree and AUTOLEDGER refuses to guess. Corrected means an automatic allocation was manually corrected. Colours are a guide, not accounting approval.'},
    {'id':'find_search','title':'Find transactions','page':'payments','keywords':'find search transaction text filter','body':'Find narrows the visible rows using text you type, such as part of a supplier name or bank reference. It changes only what you can see; it does not delete, edit or export anything.'},
    {'id':'show_filter','title':'The Show filter','page':'payments','keywords':'show all recurring unassigned amount review ambiguous assigned auto allocated corrected vat no vat selected not selected','body':'Show lets you display only a chosen type of row. Options include All, Recurring, Unassigned, Amount review, Ambiguous, Assigned, Auto-allocated, Corrected, VAT, No VAT, Selected for export and Not selected. Use All to remove this filter.'},
    {'id':'repeat_description','title':'Repeat description filter','page':'payments','keywords':'repeat description recurring description select clear','body':'Repeat description helps you find transactions whose bank descriptions repeat. Choose one of the listed repeat descriptions to narrow the table, or choose All repeat descriptions. Clear removes that repeat-description filter.'},
    {'id':'sort_date','title':'Sort date','page':'payments','keywords':'oldest newest sort date header ascending descending','body':'Sort date changes the order of visible transactions. Oldest first puts earlier dates at the top; Newest first puts later dates at the top. Clicking the Date heading can also toggle the date sort.'},
    {'id':'allocation_tools','title':'Allocation tools','page':'payments','keywords':'allocation tools assign save rule correct auto','body':'Allocation tools change how transactions are assigned to accounting accounts. Use Assign once for a one-off transaction, Save rule for future automatic matching, or Correct auto-allocation when a saved rule chose the wrong result.'},
    {'id':'assign_once','title':'Assign once','page':'payments','keywords':'assign once statement only manual allocation one off','body':'Assign once changes only the selected transaction in the current statement. Use it when this transaction is unusual and you do not want future transactions to copy the same allocation.'},
    {'id':'manual_fields','title':'Fields in Assign once','page':'payments','keywords':'gl account pastel description reference vat tax type apply','body':'GL account is the account that receives the transaction. Pastel description is the text sent to Pastel. Pastel reference identifies the entry; AUTOLEDGER normally generates final export references. VAT turns VAT treatment on or off, and Tax type must match your Pastel company. Apply saves this one-off assignment to the current statement.'},
    {'id':'save_rule_vs_once','title':'Assign once vs Save rule','page':'payments','keywords':'save rule future csv remember assignment once','body':'Assign once is temporary for this statement. Save rule teaches AUTOLEDGER to recognise the same type of bank transaction in future statements. Save a rule only when you are confident future matching transactions should normally receive the same treatment.'},
    {'id':'correct_auto','title':'Correct auto-allocation','page':'payments','keywords':'wrong gl false auto allocation correction update saved rule','body':'Use Correct auto-allocation when AUTOLEDGER automatically assigned a transaction incorrectly. You can correct only this statement or update the saved rule so future matching transactions use the new GL/description. If there is no saved rule behind the allocation, the correction can only be statement-specific.'},
    {'id':'apply_saved_rules','title':'Apply saved rules','page':'dashboard','keywords':'apply saved rules reapply refresh rules','body':'Apply saved rules runs the current profile\'s saved rules against the loaded statement again. Use it after creating or editing rules when you want the current statement to be evaluated using the latest rule settings.'},
    {'id':'rules_overview','title':'Saved Rules screen','page':'rules','keywords':'saved rules list edit delete payment receipt backup','body':'Saved Rules lists the automatic allocation instructions stored for the current company profile. You can create separate Payment and Receipt rules, Edit a selected rule, Delete a selected rule, or export/import a rules backup. Double-clicking a rule also opens it for editing.'},
    {'id':'new_rules','title':'New payment rule and New receipt rule','page':'rules','keywords':'new payment rule receipt rule direction','body':'New payment rule creates a rule for money leaving the bank. New receipt rule creates a rule for money entering the bank. A rule only applies on its own direction, so create the rule on the side where that transaction belongs.'},
    {'id':'rule_name','title':'Rule name','page':'rules','keywords':'rule name field label purpose','body':'Rule name is a friendly label for you, such as Vodacom mobile or Monthly bank fees. It helps you recognise the rule later. It does not have to match the bank wording.'},
    {'id':'match_text','title':'Name / number to match','page':'rules','keywords':'pattern match text bank reference identity name number','body':'Name / number to match is the bank wording AUTOLEDGER looks for. Use the stable part of the transaction description or reference, not a changing date or random number unless that number is part of the identity you deliberately want to match.'},
    {'id':'matching_methods','title':'Matching method','page':'rules','keywords':'smart name number contains starts with exact matching method','body':'Matching method controls how strictly AUTOLEDGER compares the saved match text with a bank transaction. Smart name + number is designed for bank references whose spacing or extra text changes. Contains matches when your text appears anywhere. Starts with matches only at the beginning. Exact requires the whole comparison text to match. Use the narrowest method that reliably identifies the intended transaction.'},
    {'id':'priority','title':'Priority in a saved rule','page':'rules','keywords':'priority higher number precedence 100 200 300 overlapping rules','body':'Priority decides which rule is considered first when more than one saved rule could match the same transaction. Higher numbers have higher priority. Leave normal rules at 100. Use 200 or 300 for a more specific exception that must beat a broader rule. Example: a general VODACOM rule at 100 and a specific VODACOM B0003783 rule at 200 means the specific rule is considered first. If priorities are equal, AUTOLEDGER prefers the more specific/longer match before its final internal tie-break.'},
    {'id':'gl_account','title':'General ledger / GL account','page':'rules','keywords':'general ledger gl account account code max 7','body':'A GL account is the Pastel General Ledger account where the transaction is allocated. Choose or type the correct account code for the accounting purpose. AUTOLEDGER warns about codes longer than Sage\'s published 7-character cash-book layout, and validation can block an invalid export.'},
    {'id':'pastel_description','title':'Pastel description','page':'rules','keywords':'pastel description optional text export','body':'Pastel description is the wording that will appear on the Pastel cash-book entry. It is optional in some places. When allocating several rows at once, leaving the description blank keeps each row\'s existing description.'},
    {'id':'pastel_reference','title':'Pastel reference','page':'rules','keywords':'pastel reference auto generated max 8 p r sequence','body':'Pastel reference is the short reference sent to the import file. Rule-level references are not reused as final transaction references; AUTOLEDGER generates final monthly Payment and Receipt sequences such as P6-0001 and R6-0001. Pastel references may not exceed 8 characters.'},
    {'id':'vat','title':'VAT treatment','page':'rules','keywords':'vat no vat inclusive tax treatment','body':'Choose No VAT when the transaction must not calculate VAT. Choose VAT only when that transaction is genuinely VAT-applicable. AUTOLEDGER calculates the VAT portion from the VAT-inclusive bank amount using the profile VAT rate, but you remain responsible for the accounting decision.'},
    {'id':'tax_type','title':'Pastel tax type','page':'rules','keywords':'tax type whole number vat pastel company','body':'Pastel tax type is the numeric tax code used by your Pastel company. When VAT is enabled, enter the correct whole-number tax type. Do not guess this number; confirm it in the correct Pastel company.'},
    {'id':'amount_rule','title':'Use amount-based allocation rule','page':'rules','keywords':'amount based allocation optional rule threshold exception','body':'An amount-based rule adds a second decision to a normal saved rule. Turn it on only when the amount changes what should happen. If the amount condition is not met, AUTOLEDGER uses the normal GL and description from the rule.'},
    {'id':'amount_condition','title':'If amount and threshold','page':'rules','keywords':'amount operator less greater equal threshold < <= > >= =','body':'Choose an operator (<, <=, >, >= or =) and enter a numeric threshold. Example: > 5000 means the special amount action applies only when the transaction amount is greater than 5,000. The threshold must be a valid number.'},
    {'id':'amount_actions','title':'Automatically allocate vs Review each qualifying transaction','page':'rules','keywords':'amount action automatically allocate review each qualifying transaction','body':'Automatically allocate sends qualifying amounts straight to the Alternative GL/description. Review each qualifying transaction does not guess; it shows those transactions in the review table so you can allocate them individually. Use Review when the amount may change the accounting purpose and a person should decide.'},
    {'id':'alternative_allocation','title':'Alternative GL and Alternative description','page':'rules','keywords':'alternative gl account alternative description amount branch','body':'Alternative GL is the account used when an automatic amount condition is met. Alternative description is the optional description used with that branch. Automatic amount allocation requires an Alternative GL.'},
    {'id':'amount_review','title':'Amount-condition review table','page':'rules','keywords':'transactions caught amount condition assign selected select all shown clear selection','body':'When an amount rule uses Review, qualifying transactions appear in the review table. Tick the rows you want to deal with, use Select all shown if every visible row should be selected, Clear selection to untick them, and Assign selected to give only those chosen rows an allocation.'},
    {'id':'rule_save_cancel','title':'Save rule and Cancel','page':'rules','keywords':'save rule cancel close editor','body':'Save rule checks the required fields and stores the rule in the current company profile. Cancel closes the rule editor without saving the new changes. Required rule fields include a rule name, match text and GL account.'},
    {'id':'recurring','title':'Recurring Payments and Recurring Receipts','page':'recurring_payments','keywords':'recurring payment receipt repeated identity history','body':'Recurring screens group transaction identities that have appeared repeatedly. They help you review repeating activity such as subscriptions or regular receipts. Recurring grouping is organisational; it does not make the rule matcher less strict.'},
    {'id':'recurring_tree','title':'Expand recurring names and identities','page':'recurring_payments','keywords':'expand recurring name identity child transaction tree','body':'In a recurring screen, expand a name to see recurring identities underneath it, then expand an identity to see individual transactions. The parent totals are summaries; each child transaction still keeps its own date, amount, allocation, VAT, rule, status and export tick.'},
    {'id':'recurring_allocation','title':'Recurring allocation tools','page':'recurring_payments','keywords':'recurring allocation assign identity individual transaction','body':'Recurring allocation tools let you allocate a selected recurring identity or individual transaction. Select the correct level first. If AUTOLEDGER asks you to expand the name, expand it and select the identity or transaction you actually want to change.'},
    {'id':'quick_select','title':'Quick select for export','page':'payments','keywords':'add auto allocated manual allocations clear all additive quick select','body':'Quick-select buttons are additive. Add Auto-Allocated ticks matching automatic rows without unticking rows already selected. Add Manual Allocations adds manual rows as well. Use both if you want both groups. Clear All removes all export ticks so you can start the selection again.'},
    {'id':'validation','title':'Validate / Check selected for errors','page':'dashboard','keywords':'validate check selected errors pre import','body':'Validate checks only the rows currently selected for export. Run it before every export. AUTOLEDGER blocks unsafe selected rows instead of silently producing a questionable Pastel file.'},
    {'id':'validation_errors','title':'Common validation and rule errors','page':'dashboard','keywords':'validation error unassigned ambiguous gl length reference tax whole number threshold','body':'Common problems include an unassigned GL, ambiguous rules, an invalid or overlong GL account, a Pastel reference longer than 8 characters, VAT with a missing/invalid tax type, non-whole Priority or tax type, or an invalid amount threshold. Read the message, correct the field or untick the row, then validate again.'},
    {'id':'export','title':'Export selected to Pastel','page':'dashboard','keywords':'export selected pastel payments receipts csv review files','body':'Export selected to Pastel creates the import files from the rows that are ticked and have passed validation. Payments and Receipts are exported separately. Import the Payment CSV into Pastel\'s Payments side and the Receipt CSV into the Receipts side, then review the imported batch before Update/Process.'},
    {'id':'receipt_sign','title':'Why receipt Bank Amount should be positive','page':'receipts','keywords':'receipt bank amount negative positive sign money in','body':'Receipts are money in. AUTOLEDGER uses the corrected receipt export sign so Pastel should show a positive Bank Amount on the Receipts side. If it appears negative, first check that you imported the Receipt CSV into Pastel\'s Receipts side.'},
    {'id':'references','title':'How final references are numbered','page':'dashboard','keywords':'references monthly sequence p6 r6 duplicate','body':'AUTOLEDGER generates separate monthly Payment and Receipt reference sequences. Examples are P6-0001 and R6-0001. This prevents a rule-level reference from being duplicated across many exported transactions.'},
    {'id':'settings_overview','title':'Settings screen','page':'settings','keywords':'settings profile company pastel configuration','body':'Settings belong to the current company profile. Check them before the first export for that company. The important fields are Cash Book bank GL account, VAT tax type, VAT rate, fiscal-year start month and optional project code.'},
    {'id':'contra_account','title':'Cash Book bank GL / Contra Account','page':'settings','keywords':'cash book bank gl contra account column l max 7','body':'This is the bank General Ledger account linked to the Pastel Cash Book. Pastel\'s CSV layout calls column L Contra Account, but it is not a different contra for every transaction. Enter the Cash Book bank GL once for the company, up to 7 characters, or leave it blank only if your Pastel import accepts blank column L.'},
    {'id':'vat_setting','title':'VAT tax type number setting','page':'settings','keywords':'vat tax type number company setting','body':'This setting is the default Pastel tax type for the current company. It is company-specific. Leave it blank until you have confirmed the correct number in Pastel.'},
    {'id':'vat_rate','title':'VAT rate (%) setting','page':'settings','keywords':'vat rate percentage 15 inclusive','body':'VAT rate is the percentage AUTOLEDGER uses when calculating VAT-inclusive amounts. The default is 15%. Change it only when the applicable rate for that company/period is different.'},
    {'id':'fiscal_month','title':'Fiscal year start month','page':'settings','keywords':'fiscal year start month period 1 12 setup periods','body':'Enter a month number from 1 to 12. AUTOLEDGER uses it to calculate Pastel period 1–12 from each transaction date. Confirm the company\'s year start in Pastel under Setup → Periods.'},
    {'id':'project_code','title':'Project code','page':'settings','keywords':'project cost code optional max 5','body':'Project code is an optional Pastel project/cost code. Leave it blank if the company does not use projects. If used, it may be up to 5 characters.'},
    {'id':'save_settings','title':'Save settings','page':'settings','keywords':'save settings profile current company','body':'Save settings writes the values on the Settings screen to the current company profile. If you switch company profiles, the other profile can have different settings.'},
    {'id':'rules_backup','title':'Export and Import rules backup','page':'rules','keywords':'export rules backup import rules backup move copy','body':'Export rules backup creates a portable backup of the current profile\'s saved rules. Import rules backup brings a rules backup into the current profile. Check the active company first so you do not import rules into the wrong workspace.'},
    {'id':'settings_backup','title':'Export settings backup','page':'settings','keywords':'export settings backup transfer settings','body':'Export settings backup saves the current profile\'s settings for safekeeping or transfer. It does not export the bank statement itself.'},
    {'id':'import_settings','title':'Import settings backup / v1.10 database','page':'settings','keywords':'import settings backup v1.10 database migrate old','body':'Import settings backup / v1.10 database is for bringing compatible settings from a backup or older supported database into the current profile. Use it only when you know which source file you are importing, and verify the settings afterward.'},
    {'id':'autosave','title':'Autosave and resume','page':'dashboard','keywords':'autosave session restore close reopen filters ticks statement','body':'When AUTOLEDGER closes normally, it saves the active profile\'s working session, including the statement, allocations, corrections, export ticks, filters, recurring view and current page. Reopening that profile restores the session. A profile switch also preserves its session for when you return.'},
    {'id':'help_search','title':'Search Help','page':'dashboard','keywords':'tutorial searchable help search answer clear search','body':'Type ordinary words into Search help, such as priority, VAT, wrong GL, backup or receipt negative. The results search the topic title, keywords and explanation. Clear search removes the query. Search changes only the help results; it does not change accounting data.'},
    {'id':'tutorial_controls','title':'Back, Next, Re-scan, Skip and Close','page':'dashboard','keywords':'back next re scan progress skip tutorial close recommended path','body':'Next moves to the next tutorial topic and Back returns to the previous one. Re-scan my progress rebuilds the tutorial path from the current workspace. Skip tutorial marks onboarding as skipped for this profile, while Close only closes the window. You can reopen Tutorial & Help at any time.'},
    {'id':'free_edition','title':'AUTOLEDGER Free limits','page':'dashboard','keywords':'free one profile 100 entries monthly limit statement','body':'Free supports one company profile and up to 100 statement transaction entries per calendar month. The whole statement is blocked if loading it would exceed the remaining allowance; AUTOLEDGER does not silently truncate it. Loading the identical statement again in the same month does not count it twice.'},
    {'id':'pro_edition','title':'AUTOLEDGER Pro','page':'dashboard','keywords':'pro unlimited profiles entries licence','body':'Pro supports unlimited company profiles and unlimited statement entries. A valid permanent Pro entitlement is stored locally and remains compatible across normal AUTOLEDGER updates.'},
    {'id':'pro_transfer','title':'Pro licence: one PC, deactivate and transfer','page':'dashboard','keywords':'pro licence device transfer deactivate replacement pc motherboard hardware','body':'One Pro licence is intended for one active PC. Minor hardware changes such as RAM, SSD or graphics-card upgrades should not normally need a transfer. For a new PC or motherboard, use Deactivate / Transfer Licence on the old PC, then install Pro on the replacement PC and enter the same permanent Pro key. If the old PC is dead, AUTOLEDGER support can reset the device activation.'},
    {'id':'privacy','title':'What leaves your PC','page':'dashboard','keywords':'privacy local data server bank accounting activation','body':'Bank statements, transactions, mappings, allocations and accounting data stay on the PC. The commercial Pro activation service is designed to receive only minimal licensing and hashed device information needed to enforce the licence; it does not need your bank or accounting data.'},
    {'id':'install_update','title':'Full install vs Update','page':'dashboard','keywords':'full standalone clean install update from r6 no python','body':'Use the FULL / Stand-alone installer on a clean PC. Use the UPDATE installer when the matching AUTOLEDGER edition is already installed. Both application packages are self-contained on supported 64-bit Windows PCs and do not require a separate Python installation. A Pro update keeps the same permanent Pro entitlement.'},
    {'id':'uninstall','title':'Uninstall and local data','page':'dashboard','keywords':'uninstall remove local data settings preserve profiles licence','body':'When uninstalling, AUTOLEDGER asks whether you also want to remove local data and settings. Choose No if you plan to reinstall or update and want to keep profiles/settings/licence data. Choose Yes only when you intentionally want that edition\'s local AUTOLEDGER data permanently removed.'},
)


def install_complete_help(core, edition: str, licence_info=None) -> None:
    """Install one complete, searchable, beginner-friendly help curriculum."""
    all_topics = [dict(t) for t in COMPLETE_HELP_TOPICS]
    core.TUTORIAL_TOPICS = tuple(all_topics)

    def _all_topic_ids(snapshot=None):
        return [t['id'] for t in core.TUTORIAL_TOPICS]

    # R9 deliberately walks every topic so the tutorial itself covers the full product.
    core.adaptive_tutorial_topic_ids = _all_topic_ids
